language: node_js
node_js:
- "stable"
notifications:
  email: false
services:
  - postgresql
TRAVIS_SECURE_ENV_VARS: true
env:
global:
  - export NODE_ENV=test
  - export DB_TEST_URL
before_script:
  - npm install
  - npm i nyc --save-dev
  - psql DB_TEST_URL
script:
  - npm test
after_success:
  - npm run coverage
  - npm run coveralls
cache:
  directories:
    - node_modules
addons:
  ssh_known_hosts: baasu.db.elephantsql.com:5432
