language: node_js
node_js:
- 8.10.0
notifications:
  email: false
services:
  - postgresql
env:
global:
before_script:
  - npm install
  - npm i nyc --save-dev
script:
  - npm run test
after_success:
  - npm run coverage
  - npm run coveralls
cache:
  directories:
    - node_modules
