language: node_js
node_js:
- "stable"
notifications:
  email: false
services:
  - postgresql
before_script:
  - npm install
  - npm i nyc --save-dev
script:
  - npm run test
after_success:
  - npm run coverage
  - npm run coveralls
cache:
  directories:
    - node_modules
env:
global:
  - global=