language: node_js
node_js:
- "stable"
notifications:
  email: false
services:
  - postgresql
TRAVIS_SECURE_ENV_VARS: true
env:
global:
  - export NODE_ENV=test
  - export timeout=10000000000
before_script:
  - npm install
  - npm i nyc --save-dev
  - psql -c 'CREATE DATABASE travis;' -U postgres
  - psql -c "CREATE USER petit WITH PASSWORD 'password';" -U postgres
script:
  - npm test
after_success:
  - npm run coverage
  - npm run coveralls
cache:
  directories:
    - node_modules
